### ISSUE TITLE
zfpy windows

### ISSUE THREAD

**Issue by ToreAad** [conda-forge/zfpy-feedstock#5]
Hi!

It would be nice to have a precompiled package with zfpy for windows users. I have made a pull requests that adds a working windows build recipe to this feedstock. I would be very grateful if you took the time to review the pull-request and considered to merge it with your repository.

Here is a link to the pull request:
https://github.com/conda-forge/zfpy-feedstock/pull/4

Kind regards,
Tore Aadland

**Comment by hmaarrfk** [comment]
Seems good now!

Thanks for your patience.
